language: node_js
node_js:
  - "7"

build:
  - npm run build:prod

deploy:
  provider: pages
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: dist
  on:
    branch: master
